const tinyPaddingSize = 8;
const largePaddingSize = 20;
const mobileSize = 788;
export const tinyPaddingSizeCss = `${tinyPaddingSize}px`;
export const largePaddingSizeCss = `${largePaddingSize}px`;
export const baseSpace = `1.25rem`;
export const halfBaseSpace = `0.625rem`;
export const desktopMaxWidth = `1024px`;
export const mobileBreakpoint = `screen and (max-width: ${mobileSize}px)`;
