kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: argo-istio-rbac
  namespace: doc-index-updater
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: argo-istio
  namespace: doc-index-updater
subjects:
  - kind: ServiceAccount
    name: argocd-application-controller
    namespace: argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argo-istio-rbac
