apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: delete-queue-policy-key
  namespace: doc-index-updater
spec:
  encryptedData:
    key: AgBfknY0QUrsKUzXIrFVlwFPTi9GJV9khrEGcNvMmEVARGIuAT7jNZhsFqw5oKT1H39KGbI8ASUp/i6U7bSQCy/EYNe6L60i2XjOahLgFFNMXrVJJsjazSax8hUXR5nDgJGEMrXRJo3afE2fPMsLVTJ1uahp1At0lsRTTLL3A8T2WnpXdbinvip/dt9nabITZt7Xcw8xHGT4pG1F8CrXTRYKdP40iNGJ2fpKzGHwVMnEBTI19uXXWavWMqTjKv9sGU95IWTkrvRUOqCnfIM/kzswKx24KUb0n8Pvm5ECzgheenSUM9qHfUQ1goV2IZrqTpzc801bwmv5b6XXdgtxGUBTlR9mFByAT6vXV1i+RSTFXolUk7lZG8qdbfkPDauRvutPXr2rmqAqXe/MNWStg6X4cpb0tAtS4cw2J2jv5ZXkQUMxHcTKlt6bemO5N/BLfK11iMPRyT0DQ4fcH44AlnkqlOIz9zN8ViiRwp6kWMBt/yd/sp5VWEqxN6+Af4kBx7JzDSU9jU9JvRUneMSoufsZxlqO6NIuNkwWGHWNCP6BE2/e8NcTzCY4Ghonaf9VYisAheCLIrry9m6bUJgNlRoVPWUYXdrwMfpEdLNo4g4zAXXPlE2qLBpSOp/+dTG0uNrkUC4uOb62zZ5bXR/uA3bEEKpzP0lCuLzDy5bXAC7LyDGst0jA2Fe1uAMjSKAAgKt7HNETBHMxjuxsF8Jvw2ogh/eW4KRIezkdQF6CZYjzjw174VTW9XcYd+uPwQ==
  template:
    metadata:
      creationTimestamp: null
      name: delete-queue-policy-key
      namespace: doc-index-updater
status: {}

